### ISSUE TITLE
Feature Request: Websocket support

### ISSUE THREAD

**Issue by marek22k** [ronin-rb/ronin-support-web#5]
Hello,

Ronin provides great features with `tcp_accept` and `tcp_server_loop`. I would like if Ronin also has websocket support , for example with functions like `ws_accept` or `ws_server_loop`.

**Comment by postmodern** [comment]
This is a great idea. However, it would require adding an additional dependency for a websocket library. I have been thinking about maybe making a `ronin-support-web` library, and moving some of the methods out of [ronin-web](https://github.com/ronin-rb/ronin-web). Depends on whether people want `ronin-support` to have everything out of the box, or keep more high-level web stuff in a separate library?

**Comment by postmodern** [comment]
Would it be acceptable if `websocket_*`/`ws_*` methods were accessible in the `ronin-web irb` console? Or would you want them accessible in the main `ronin irb` console as well?

**Comment by postmodern** [comment]
Evaluating possible websocket libraries that can wrap around a basic `TCPSocket` or `SSLSocket`:

* [websocket-ruby](https://github.com/imanel/websocket-ruby)
* [protocol-websocket](https://github.com/socketry/protocol-websocket/blob/main/guides/getting-started/README.md)

**Comment by postmodern** [comment]
Also going to need more details on how you'd like to use the resulting socket object. The majority of Ruby websocket libraries provide an async/callback interface. I could however create my own `WebSocket` class that wraps around `TCPSocket` or `SSLSocket` and uses `websocket-ruby` or `protocol-websocket` to synchronously read/write websocket frames.

**Comment by postmodern** [comment]
Here's a crude prototype of using the `websocket-ruby` library to perform the WebSocket/HTTP upgrade and then encode/decode frames.

```ruby
require 'websocket'
require 'socket'

socket = TCPSocket.new('ws.vi-server.org',80)

handshake = WebSocket::Handshake::Client.new(url: 'ws://ws.vi-server.org/mirror')
socket.write(handshake)
handshake << socket.readpartial(1024)

puts "Handshake complete" if handshake.finished?
puts "Handshake valid" if handshake.valid?

frame = WebSocket::Frame::Outgoing::Client.new(version: handshake.version, data: 'abc123', type: :text)
socket.write(frame)

frame = WebSocket::Frame::Incoming::Client.new(version: handshake.version)
frame << socket.readpartial(1024)

p frame.next
p frame.next

socket.close
```

```
Handshake complete
Handshake valid
<WebSocket::Frame::Incoming::Client:0x000005b4 @decoded=true, @type=:text, @code=nil, @data="abc123", @version=13, @handler=#<WebSocket::Frame::Handler::Handler07:0x00007f3932f0ce28 @frame=<WebSocket::Frame::Incoming::Client:0x000005b4 @decoded=true, @type=:text, @code=nil, @data="abc123", @version=13, @handler=#<WebSocket::Frame::Handler::Handler07:0x00007f3932f0ce28 ...>>, @application_data_buffer=nil>>
nil
```

It would be possible to create a `WebSocket` class which wraps around an underlying `TCPSocket` or `SSLSocket`, and provides the usual socket methods like `write` or `recv` to handle sending/receiving frames. It probably wouldn't make sense to implement buffered IO on top of a websocket, since it's a message based protocol, not a streaming IO protocol.

**Comment by marek22k** [comment]
> Would it be acceptable if `websocket_*`/`ws_*` methods were accessible in the `ronin-web irb` console? Or would you want them accessible in the main `ronin irb` console as well?

For me personally, this is irrelevant as I would use the function in a Ruby script and not in a console.
Maybe it would make sense to do it the same way as with TCP?

> Also going to need more details on how you'd like to use the resulting socket object.

Personally, I would like to be able to treat the websocket object like a TCPSocket.
```sh
require 'json'
require 'ronin/support/network/ws'

include Ronin::Support::Network::WS

ws_connect(endpoint: 'ws://lg.reseau.mk16.de/ws') do |client|
  client.puts JSON.dump(["test", 1, 3, 4])
  result = JSON.load clients.gets
end
```
Instead of writing `ws` it might look nicer to write `websocket` in some places.

**Comment by postmodern** [comment]
> Maybe it would make sense to do it the same way as with TCP?

If you're using the methods in a script, then you'd need to do something similar to how to load `ronin-support` into a script:

```ruby
require 'ronin/support/web'
include Ronin::Support::Web
```

or if you only wanted the `websocket_*` functions, `require 'ronin/support/web/websocket'` and `include Ronin::Support::Web::WebSocket::Mixin`.

**Comment by postmodern** [comment]
Any opinions on how the underlying classes should be named, if someone wanted to directly use them in the same way that one would use `TCPSocket` or `TCPServer`?

**Comment by marek22k** [comment]
Maybe `WSSocket` and `WSServer`, but I'm pretty bad at naming things.

**Comment by postmodern** [comment]
Alright, I finally got the code written and working-ish.
https://github.com/ronin-rb/ronin-support-web/compare/main...websocket

```ruby
include Ronin::Support::Web::WebSocket::Mixin

websocket = websocket_connect('ws://websocket-echo.com')
websocket.send_frame("foo bar")
# => 13
websocket.recv_frame
# => <WebSocket::Frame::Incoming::Client:0x000227a4 @decoded=true, @code=nil, @data="foo bar", @version=13, @handler=#<WebSocket::Frame::Handler::Handler07:0x00007f7d4c9b0ed0 @frame=<WebSocket::Frame::Incoming::Client:0x000227a4 @decoded=true, @code=nil, @data="foo bar", @version=13, @handler=#<WebSocket::Frame::Handler::Handler07:0x00007f7d4c9b0ed0 ...>, @type=:text>, @application_data_buffer=nil>, @type=:text>
websocket.send_frame("hello world")
# => 17
websocket.recv
# => "hello world"
```

```ruby
server = websocket_server('ws://localhost:1337/')
client = server.accept
client.send("hello")
client.recv
# => "good, how are you"
```
```ruby
client = websocket_client('ws://localhost:1337/')
client.recv
# => "hello"
client.send("good, how are you")
```

I still need to get the `WebSocket::Server` working with `wss://` URLs which need to spawn a SSL/TLS server. This will probably require adding a custom `Ronin::Support::Network::SSL::Server` class that wraps around `TCPServer` and returns an `SSLSocket` when `server.accept` is called.

**Comment by postmodern** [comment]
I finally got all of the specs written for all of the helper methods. DONE!

**Comment by postmodern** [comment]
@marek22k FYI this feature has now been released and you can play with it in `ronin-web irb`!

```
$ ronin-web irb
irb(ronin-web)> ws = ws_connect('websocket-echo.com')
=> 
#<Ronin::Support::Web::WebSocket::Client:0x00007f9178992940
...
irb(ronin-web)> ws.send("hello")
=> 11
irb(ronin-web)> ws.recv
=> "hello"
```

**Comment by marek22k** [comment]
Thank you for implementing this feature!
